use bashlib submodule in place of individual files

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,9 +1,35 @@
 #!/bin/bash
 
 #----------------------------------------------------------------------------------------------
-#
-#   deploy.bashlib; basic functions to run a cluster docker environment
-#
+function deploy.usage()
+{
+    local -i exit_status=${1:-1}
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+
+    cat >&2 << EOF
+Usage:
+    $progname [ -h|--help ]
+              | [ --clean ]
+              | [ --down ]
+              | [ --init ]
+              | [ --latest ]
+              | [ --promote <branch> ]
+
+    Common options:
+        -h --help              Display a basic set of usage instructions
+        -c --clean             0:do not clean environment
+                               1:clean environment before build (default)
+        -d --down              stop services defined by 'docker-compose.yml'
+        -i --init              only initialize the environment
+        -l --latest            update to latest versions of images rather than using those defined in docker-compose.yml
+        -p --promote <branch>  promote images in docker repo, from current <branch> to target <branch>
+                               this retags the image with the target <branch>, 
+                                   on protected branches {eg: master or integration } the ':latest' tag is used
+                               after a pull request has completed the new images should be pushed to the registry.
+
+EOF
+    exit "$exit_status"
+}
 
 #----------------------------------------------------------------------------------------------
 # initialize global variables
@@ -108,6 +134,40 @@ function deploy.clean()
     # remove workspace folder
     term.log "\$rm -rf $WORKSPACE_DIR"'\n' 'grey'
     sudo rm -rf "$WORKSPACE_DIR"
+}
+
+#----------------------------------------------------------------------------------------------
+function deploy.cmdLineArgs()
+{
+    local base="${1:?}"
+    shift
+    local usage='deploy.usage'
+
+    # Parse command-line options into above variable
+    local -r longOpts='help,Help,HELP,clean,down,init,latest,promote:'
+    local -r shortOpts='Hhcdilp:'
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+    local -r options=$(getopt --longoptions "$longOpts" --options "$shortOpts" --name "$progname" -- "$@") || "$usage" $?
+    eval set -- "$options"
+
+    local -A opts=()
+    [ "$base" ] && opts['base']="$base" 
+    while true; do
+        case "${1:-}" in
+            -h|--h|--help|-help)  "$usage" 1;;
+            -H|--H|--HELP|-HELP)  "$usage" 1;;
+            --Help|-Help)         "$usage" 1;;
+            -c|--c|--clean)       opts['clean']=1;         shift;;
+            -d|--d|--down)        opts['down']=1;          shift;;
+            -i|--i|--init)        opts['init']=1;          shift;;
+            -l|--l|--latest)      opts['latest']='latest'; shift;;
+            -p|--p|--promote)     opts['promote']=$2;    shift 2;;
+            --)                   shift; break;;
+        esac
+    done
+    
+    [ $# -eq 0 ] || term.log 'Ignoring extra arguments' 'warn'
+    appenv.results
 }
 
 #----------------------------------------------------------------------------------------------
@@ -479,7 +539,7 @@ export -f deploy.replaceIpAddresses
 #----------------------------------------------------------------------------------------------
 function deploy.restart()
 {
-    echo "CONTAINER_TAG: ${CONTAINER_TAG:-}" >&2
+    echo "CONTAINER_TAG: ${CONTAINER_TAG:-<using default>}" >&2
 
     # initialize workspace if required 'docker-compose.yml' is missing
     mkdir -p "$WORKSPACE_DIR" ||:
@@ -793,3 +853,22 @@ function deploy.workspace()
 }
 
 #----------------------------------------------------------------------------------------------
+#
+#      MAIN
+#
+#----------------------------------------------------------------------------------------------
+
+declare -i status
+declare -a args
+declare fn=deploy.main
+declare loader="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/appenv.bashlib"
+if [ ! -e "$loader" ]; then
+    echo 'Unable to load libraries'
+    exit 1
+fi
+
+source "$loader"
+appenv.loader "$fn"
+
+args=( $( deploy.cmdLineArgs "$TOP" "$@" ) ) && status=$? || status=$?
+[ $status -eq 0 ] && "$fn" "${args[@]}" 
