use bashlib submodule in place of individual files

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,9 +1,35 @@
 #!/bin/bash
 
 #----------------------------------------------------------------------------------------------
-#
-#   deploy.bashlib; basic functions to run a cluster docker environment
-#
+function deploy.usage()
+{
+    local -i exit_status=${1:-1}
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+
+    cat >&2 << EOF
+Usage:
+    $progname [ -h|--help ]
+              | [ --clean ]
+              | [ --down ]
+              | [ --init ]
+              | [ --latest ]
+              | [ --promote <branch> ]
+
+    Common options:
+        -h --help              Display a basic set of usage instructions
+        -c --clean             0:do not clean environment
+                               1:clean environment before build (default)
+        -d --down              stop services defined by 'docker-compose.yml'
+        -i --init              only initialize the environment
+        -l --latest            update to latest versions of images rather than using those defined in docker-compose.yml
+        -p --promote <branch>  promote images in docker repo, from current <branch> to target <branch>
+                               this retags the image with the target <branch>,
+                                   on protected branches {eg: master or integration } the ':latest' tag is used
+                               after a pull request has completed the new images should be pushed to the registry.
+
+EOF
+    exit "$exit_status"
+}
 
 #----------------------------------------------------------------------------------------------
 # initialize global variables
@@ -111,6 +137,40 @@ function deploy.clean()
 }
 
 #----------------------------------------------------------------------------------------------
+function deploy.cmdLineArgs()
+{
+    local base="${1:?}"
+    shift
+    local usage='deploy.usage'
+
+    # Parse command-line options into above variable
+    local -r longOpts='help,Help,HELP,clean,down,init,latest,promote:'
+    local -r shortOpts='Hhcdilp:'
+    local -r progname="$( basename "${BASH_SOURCE[0]}" )"
+    local -r options=$(getopt --longoptions "$longOpts" --options "$shortOpts" --name "$progname" -- "$@") || "$usage" $?
+    eval set -- "$options"
+
+    local -A opts=()
+    [ "$base" ] && opts['base']="$base"
+    while true; do
+        case "${1:-}" in
+            -h|--h|--help|-help)  "$usage" 1;;
+            -H|--H|--HELP|-HELP)  "$usage" 1;;
+            --Help|-Help)         "$usage" 1;;
+            -c|--c|--clean)       opts['clean']=1;         shift;;
+            -d|--d|--down)        opts['down']=1;          shift;;
+            -i|--i|--init)        opts['init']=1;          shift;;
+            -l|--l|--latest)      opts['latest']='latest'; shift;;
+            -p|--p|--promote)     opts['promote']=$2;    shift 2;;
+            --)                   shift; break;;
+        esac
+    done
+
+    [ $# -eq 0 ] || term.log 'Ignoring extra arguments' 'warn'
+    appenv.results
+}
+
+#----------------------------------------------------------------------------------------------
 function deploy.containerTag()
 {
     local -r container_tag=${1:-}
@@ -127,7 +187,7 @@ function deploy.containerTag()
 function deploy.containerVersion()
 {
     local -r line=${1:?}
-    local -r json=${2:?}
+    local -r service=${2:?}
 
     local fingerprint newline orgline prefix production promoted
 
@@ -136,34 +196,31 @@ function deploy.containerVersion()
 
     newline="${line:${#prefix}}"   # strip prefix from line
     promoted="$newline"
-    production="$(unset CONTAINER_TAG; eval echo $promoted)"
+    orgimage="$(unset CONTAINER_TAG; eval echo $newline)"
+    production="$orgimage"
     fingerprint='<none>'
 
-    local image="${promoted%:*}"
-    [ "$image" = *CONTAINER_TAG ] && newline="${newline%:\${CONTAINER_TAG*}"
-    orgimage="$production"
-
-    # find service that defines image
-    local -r service=$(deploy.serviceAssociatedWithImage "$image" "$json")
-    if [ "${service:-}" ]; then
+    # only process lines which have 'CONTAINER_TAG'
+    if [[ "$newline" = *CONTAINER_TAG* ]]; then
         local container=$(jq -r '.container_name' <<< "$service")
         if [ "${container:-}" ]; then
+
+            # strip :tag'  suffix
+            newline="${newline%:*}"
+            [[ "$newline" = *CONTAINER_TAG ]] && newline="${newline%:\${CONTAINER_TAG*}"
 
             # since this service is running, extract the image name from service, and its fingerprint
             orgimage="$(docker inspect "$container" | jq -r '.[].Config.Image')"
             fingerprint=$(docker inspect "$container" | jq -r '.[].Config.Labels."container.fingerprint"')
 
             # if the fingerprint exists, replace image tag with fingerprint
-            if [ "$fingerprint" != 'null' ]; then
-                # strip :tag'  suffix
-                newline="${newline%:*}"
-                [ "$newline" = *CONTAINER_TAG ] && newline="${newline%:\${CONTAINER_TAG*}"
+            [ "$fingerprint" != 'null' ] && newline=${newline}':${CONTAINER_TAG:-'${fingerprint}'}'
 
-                newline=${newline}':${CONTAINER_TAG:-'${fingerprint}'}'
-            fi
             promoted="$(eval echo $newline)"
             production="$(unset CONTAINER_TAG; eval echo $newline)"
         fi
+    else
+        promoted="$production"
     fi
 
     # generate our output JSON
@@ -185,18 +242,19 @@ function deploy.createVolumeFolders()
     local json="${1:?}"
     local service_name="${2:?}"
 
-    local -a dirs=(jq '.' "$json" )
+    local -a dirs=()
+    # find 'volumes'; remove container mount (after ':'); exclude any which start with '/' or '~'
     mapfile -t dirs < <(jq -r ".services.${service_name}.volumes[]?" <<< "$json" \
                        | awk -F ':' '{print $1}' \
-                       | grep -v '/docker' \
-                       | grep -Ev '^~' \
+                       | grep -Ev '^[/~]' \
                        | sort -u ||:)
-    [ "${#dirs[*]}" -gt 0 ] || continue
+    [ "${#dirs[*]}" -eq 0 ] && return 0
 
     local dir
     for dir in "${dirs[@]}"; do
         [ "${dir:0:2}" = './' ] && dir="${dir:2}"                        # remove './' prefix
-        # initialize dir when needed
+        # initialize dir when needed. check if there is a coresponding CONFIG file, and strip filename when file exists
+        [ -f "${CONFIG_DIR}/$dir" ] && dir="$(dirname "$dir")"
         if [ ! -d "$dir" ]; then
             mkdir -p "$dir" ||:
             sudo chown "$EUID" "$dir"
@@ -211,6 +269,7 @@ function deploy.createVolumeFolders()
             ln -s "${WORKSPACE_DIR}/$dir" "${LOG_DIR}/$service_name"
         fi
     done
+    return 0
 }
 
 #----------------------------------------------------------------------------------------------
@@ -219,9 +278,9 @@ function deploy.createVolumeFolders()
 function deploy.fixupDCLineAfterRun()
 {
     local line="${1:?}"
-    local property="${2:?}"       # property for 'jq' to select from JSON:  '.newline' or '.promoted'
-    local json="${3:?}"
-    local isConfig="${4:-}"
+    local -r service="${2:?}"
+    local -r property="${3:?}"       # property for 'jq' to select from JSON:  '.newline' or '.promoted'
+    local -r isConfig="${4:-}"
 
     # don't copy comments to output
     [ -z "${isConfig:-}" ] && grep -Eq '^\s*#' <<< "$line" && return 0
@@ -229,7 +288,7 @@ function deploy.fixupDCLineAfterRun()
     # update image definition
     if grep -qsE '^\s+image:\s' <<< "$line"; then
         # update workspace/docker-compose.yml when we pull latest images
-        line="$(deploy.containerVersion "$line" "$json" | jq -r "$property")"
+        line="$(deploy.containerVersion "$line" "$service" | jq -r "$property")"
     fi
 
     # update any versions.  (search for string containing  '${SOMEMODULE_VERSION:-xxxxxxxxxxxxxxx}'
@@ -254,6 +313,7 @@ function deploy.fixupDCLineAfterRun()
 function deploy.fixupDCLineBeforeRun()
 {
     local line="${1:?}"
+    local -r service="${2:?}"
 
     # don't copy comments to output
     grep -Eq '^\s*#' <<< "$line" && return 0
@@ -265,8 +325,8 @@ function deploy.fixupDCLineBeforeRun()
     done < <(awk '/([A-Z0-9]+_VERSION):-/ {sub(":.*","");print substr($0,2)}' RS='$' <<< "$line")
 
     # update default OS with actual OS from container.os file
-    local -r os=$(sed -E 's|^\s+.+\$\{(CONTAINER_OS):-[^}]+}.*$|\1|' <<< "$line")
-    if [ "${CONTAINER_OS}" != "$os" ] && grep -qsE 'alpine' <<< "$line"; then
+    local -r os=$(sed -E 's|^\s+.+\$\{CONTAINER_OS:-([^}]+)}.*$|\1|' <<< "$line")
+    if grep -qsE 'CONTAINER_OS' <<< "$line" && [ "${CONTAINER_OS}" != "$os" ]; then
         line="$(sed -e 's|'"${os}"'|'"${CONTAINER_OS}"'|' <<< "$line")"
 
     # if line has required content [ ex: ${HOST:?} ], then attempt to resolve
@@ -361,10 +421,6 @@ function deploy.main()
     #  restart devops_container_environment  (performs configuration if needed)
     term.log '$deploy.restart 2>&1 | tee restart.log\n' 'grey'
     deploy.restart 2>&1 | tee "${WORKSPACE_DIR}/restart.log"
-
-
-    #  update production files if this is for promotion
-    [ -z "${opts['promote']:-}" ] || deploy.toProduction
 }
 
 #----------------------------------------------------------------------------------------------
@@ -479,7 +535,7 @@ export -f deploy.replaceIpAddresses
 #----------------------------------------------------------------------------------------------
 function deploy.restart()
 {
-    echo "CONTAINER_TAG: ${CONTAINER_TAG:-}" >&2
+    echo "CONTAINER_TAG: ${CONTAINER_TAG:-<using default>}" >&2
 
     # initialize workspace if required 'docker-compose.yml' is missing
     mkdir -p "$WORKSPACE_DIR" ||:
@@ -540,9 +596,10 @@ function deploy.restartContainers()
 
     # fixup docker-compose.yml to reflect the image versions in use
     if [ "${CONTAINER_TAG:-}" = 'latest' ]; then
+        echo
         # Updating reference docker-compose.yml
-#        deploy.updateDockerCompose 'promote'
         deploy.updateDockerCompose 'updateWsYaml'
+        deploy.updateDockerCompose 'updateCfgYaml'
     fi
     return 0
 }
@@ -565,25 +622,6 @@ function deploy.reTagImages()
             term.log "no images matching $image"'\n' 'warn'
         fi
     done < <(grep -E '^\s+image:\s' "$dc_yaml" | sed -E -e 's|^\s+image:\s+||' )
-}
-
-#----------------------------------------------------------------------------------------------
-function deploy.serviceAssociatedWithImage()
-{
-    local -r image=${1:?}
-    local -r json=${2:?}
-
-    # extract images from docker-compose
-    while read -r srvc; do
-        service=$(jq ".services.$srvc" <<< "$json")
-        # match ignoring registry part of image
-        [[ $(jq -r '.image' <<< "$service") = *$image* ]] || continue
-
-        echo $service
-        return 0
-
-    done < <(jq -r '.services|keys[]' <<< "$json")
-    return 1
 }
 
 #----------------------------------------------------------------------------------------------
@@ -643,7 +681,7 @@ function deploy.updateDockerCompose()
             dst_yaml="${WORKSPACE_DIR}/docker-compose.yml"
             process='deploy.fixupDCLineAfterRun'
             json=$(docker.yamlToJson "$dst_yaml")
-            args=( '.newline' "$json" )
+            args=( '.newline' )
             ;;
 
         updateCfgYaml)
@@ -651,7 +689,7 @@ function deploy.updateDockerCompose()
             dst_yaml="$CONFIG_YAML"
             process='deploy.fixupDCLineAfterRun'
             json=$(docker.yamlToJson "$dst_yaml")
-            args=( '.newline' "$json" 'isConfig' )
+            args=( '.newline' 'isConfig' )
             ;;
 
         promote)
@@ -659,7 +697,7 @@ function deploy.updateDockerCompose()
             dst_yaml="$CONFIG_YAML"
             process='deploy.fixupDCLineAfterRun'
             json=$(docker.yamlToJson "$dst_yaml")
-            args=( '.promoted' "$json" 'isConfig' )
+            args=( '.promoted' 'isConfig' )
             ;;
 
         production)
@@ -667,7 +705,7 @@ function deploy.updateDockerCompose()
             dst_yaml="$CONFIG_DIR/docker-compose.master.yml"
             process='deploy.fixupDCLineAfterRun'
             json=$(docker.yamlToJson "${WORKSPACE_DIR}/docker-compose.yml")
-            args=( '.production' "$json" 'isConfig' )
+            args=( '.production' 'isConfig' )
             ;;
 
         *)
@@ -675,12 +713,32 @@ function deploy.updateDockerCompose()
             ;;
     esac
 
+
+    local -a services="$(docker.yamlToJson "$src_yaml" | jq -r '.services|keys[]')"
     local tmp_file="${dst_yaml#.*}.tmp"
     (
+        local service='null'
+        local key=''
         while read -r line; do
+
+            # skip blank lines
             if [ -z "${line:-}" ] || grep -sq '^\s+$' <<< "$line" ; then
                 echo
-            elif ! "$process" "$line" "${args[@]}"; then
+                continue
+            fi
+
+            # look for 'service' definition
+            key="$(sed -E -e 's|^\s+(\w+):\s*$|\1|' <<< "$line")"
+            if [ "${key:-}" ] && [ "${json:-}" ]; then
+
+                # find service that defines image
+                grep -qE '^\s+'${key}':\s*$' <<< "$line" && \
+                    grep -q "$key" <<< "$services" && \
+                    service=$(jq ".services.$key" <<< "$json")
+            fi
+
+            # process line
+            if ! "$process" "$line" "$service" "${args[@]}"; then
                 term.elog "Failed to process $line"'\n' 'warn'
                 break
             fi
@@ -695,7 +753,7 @@ function deploy.updateDockerCompose()
 
     # otherwise rename 'src_yaml' to file.YYYYMMDDhhmmss.bak and rename updated file to 'dst_yaml'
     # create backup of dstfile before we update it
-    term.log "\nINFO: updating ${dst_yaml}"'\n' 'white'
+    term.log "INFO: updating ${dst_yaml}"'\n' 'white'
     if [ -f "$dst_yaml" ]; then
         local backup="${dst_yaml%.*}.$(date +"%Y%m%d%H%M%S").${dst_yaml##*.}.bak"
         backup="$(dirname "$backup")/~$(basename "$backup")"
@@ -793,3 +851,22 @@ function deploy.workspace()
 }
 
 #----------------------------------------------------------------------------------------------
+#
+#      MAIN
+#
+#----------------------------------------------------------------------------------------------
+
+declare -i status
+declare -a args
+declare fn=deploy.main
+declare loader="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/appenv.bashlib"
+if [ ! -e "$loader" ]; then
+    echo 'Unable to load libraries'
+    exit 1
+fi
+
+source "$loader"
+appenv.loader "$fn"
+
+args=( $( deploy.cmdLineArgs "$TOP" "$@" ) ) && status=$? || status=$?
+[ $status -eq 0 ] && "$fn" "${args[@]}"
